# Generated by Django 3.2.9 on 2022-01-15 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tontine', '0002_remove_cotisation_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotisation',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Tontine.myuser'),
            preserve_default=False,
        ),
    ]
