# Generated by Django 3.2.9 on 2022-01-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tontine', '0003_cotisation_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotisation',
            name='cycle',
            field=models.CharField(blank=True, choices=[('Hebdomaider', 'Hebdomaider'), ('Menseule', 'Menseule'), ('Trimestriel', 'Trimestriel'), ('Semestriel', 'Semestriel'), ('Annuelle', 'Annuelle')], max_length=40),
        ),
    ]
