# Generated by Django 3.2.9 on 2022-01-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tontine', '0004_alter_cotisation_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotisation',
            name='cycle',
            field=models.CharField(blank=True, choices=[('journalier', 'journalier'), ('Hebdomaider', 'Hebdomaider'), ('Menseule', 'Menseule'), ('Trimestriel', 'Trimestriel'), ('Semestriel', 'Semestriel'), ('Annuelle', 'Annuelle')], max_length=40),
        ),
    ]
