# Generated by Django 4.0.1 on 2022-12-08 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tontine', '0005_alter_cotisation_cycle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidat',
            options={'ordering': ['-nombre_de_voix']},
        ),
        migrations.AlterModelOptions(
            name='election',
            options={'ordering': ['date']},
        ),
    ]
