from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('mes_tontine/<int:id>/', views.mes_tontine, name='mes_tontine'),
    path('mes_reunion/', views.mes_reunion, name='mes_reunion'),
    path('profile/<int:id>/', views.profile, name='profile'),
    path('creation_tontine/', views.create_tontine, name="create_tontine"),
    path('creation_reunion/', views.create_reunion, name="create_reunion"),
    path('tontine/<int:id>/', views.tontine, name='tontine'),
    path('tontines/', views.info_tontine, name='tontines'),
    path('reunions/', views.info_reunion, name='reunions'),
    path('creer_reunion/<int:idtontine>/',
         views.create_meeting, name='create_meeting'),
    path('creer_election/<int:idtontine>/',
         views.create_election, name='creer_election'),
    path('deposer_canidature/<int:idtontine>/', views.deposer_candidature,
         name='deposer_candidature'),
    path('confirmer_candidature/<int:idelection>/',
         views.confirmer_depos, name='confirmer_depos'),
    path('election/<int:idtontine>/',
         views.selection_election, name='select_election'),
    path('voter/<int:idelection>/', views.Voter, name="aller_voter"),
    path('confirmer_vote/', views.confirmer_vote, name='confirmer_vote'),
    path('confirmer_vote_president/<int:idelection>/',
         views.confirmer_vote_president, name="voter_president"),
    path('confirmer_vote_tresorier/<int:idelection>/',
         views.confirmer_vote_tresorier, name="voter_tresorier"),
    path('confirmer_vote_commisaire/<int:idelection>/',
         views.confirmer_vote_commisaire, name="voter_commisaire"),
    path('confirmer_vote_secreataire/<int:idelection>/',
         views.confirmer_vote_secreataire, name="voter_secretaire"),
    path('resultat_election/<int:idtontine>/',
         views.resultat_election, name='resultat_election'),
    path('demande_invitation/<int:idtontine>/',
         views.envoyer_unenotification, name="envoyer_unenotification"),
    path('notification/', views.recevoir_notification, name='mes_notification'),
    path('accepter_demande/', views.accepter_invitation, name='accepter_demande'),
    path('getNotification/', views.count_notif, name='getNotif'),
    path('modify_profile/', views.modifier_profile, name='modify_profile'),
    path('creation_fond/<int:idtontine>/',
         views.creer_fond, name='create_fond'),
    path('creer_cotisation/<int:idtontine>/',
         views.creer_cotisation, name="create_cotisation"),

]
